### PR TITLE
[WIP, HELP NEEDED] Fix many issues

### PR DESCRIPTION
**Pull request by kdmurray91**
Hi,

This started as a fix for #19 , but has grown somewhat.

So far I have:

- Fixed memory consumption issues (#8, #19, and probably #3) by storing only mail file names (not whole `Message` objects) while detecting possible duplicate mails. The `Messsage` objects are loaded from disk while processing clusters of mail files that have the same hash.
- Fixed the `cmp` issue described in #34 
- Attempted to fix several issues with encodings #32 . I have rudimentary fixes forcing decoding of the message lines, but there are still issues. Any help is welcome.
- Added a progress bar in place of printing a '.' every 100 messages

Cheers,
Kevin

### CODE REVIEW

**Comment by kdmurray91** [comment]
For the encoding challenge, I suggest we try decoding with `ascii`, then `utf-8` then run `chardet`. Failing all that I'm not sure what the best method would be.

**Comment by kdeldycke** [comment]
Thanks for the PR! I'm going to review it soon. Do you plan to commit some more stuff or is it ready to merge?

Do you have the courage of adding a couple of unit-tests? Even one or two would be great.

**Comment by kdmurray91** [comment]
Ah, it appears to be working for me, but some review and testing especially of the encoding handling would be good. I'll take a look at tests.

**Comment by kdmurray91** [comment]
There is another issue. I have vim automatically running pylint, and it detects an undefined variable. Clearly I haven't reached this code path, and I can't tell what the variable should be. Could you take a look at [this line](https://github.com/kdeldycke/maildir-deduplicate/blob/develop/maildir_deduplicate/deduplicate.py#L198) please?

**Comment by kdeldycke** [comment]
Tracked the `date_only` variable back to c87818c0b47b779ee5ea6eaf6929047ce811b791 , but it looks like I introduced the issue right after in e8477974d37f07d705aab2e420adab7ed4034598 .

This really makes me sad. There nothing to prevent anybody to push mistakes. Maildir-deduplicate is really helpful for a lot of people, but the code quality is not very good. Essentially because of its patchy history. If you plan to rely on it for important data, I'll be really happy to merge some unit-tests. Even a 10% in increased coverage would be a great leap forward.

**Comment by kdmurray91** [comment]
Working on a super basic test. Don't have heaps of time, but should at least test maildir handling.

**Comment by kdeldycke** [comment]
@kdmurray91 That's the spirit! If you can only bootstrap the unit-tests of the project, it would be easier, little by little, to improve the whole thing.

As for the `date_only` return, I cleaned it up in 7c191f5cf28045fc690abe54d728053f230b61b4 .

**Comment by kdeldycke** [comment]
This PR is good to merged IMHO. Just waiting for the last unittest commit.

I'll probably do a proper release on PyPi after this one is merged.

**Comment by kdmurray91** [comment]
The test I have written is really basic, and could do with extension if you have a little time. (it's bedtime in Australia).

Things to do:
- test other strategies
- test use of message ids
- test on maildir without any dups
- make the testing function check the presence of a list of files, and assert that no extras are present.
- make the test class copy maildirs to a temp directory, then test without dry-runs


I'm happy for you to merge & release this as you see fit. There can always be more PRs.
Cheers,
K

**Comment by kdeldycke** [comment]
Thanks @kdmurray91 ! Just waiting for the tests to pass. Then I'll merge it right away.

**Comment by kdeldycke** [comment]
Looks like maildirs are expected to have their `new` subfolder.

**Comment by kdmurray91** [comment]
Ah, of course. git won't keep them as they are empty. Doh.

**Comment by kdmurray91** [comment]
Fix incoming

**Comment by kdmurray91** [comment]
Looks like I've screwed up the silencing of the logs. If you can easily work this out, go ahead and merge and fix this then merge (I've added you as a collaborator on my repo). Otherwise I'll do it tomorow.

**Comment by kdeldycke** [comment]
I'll merge the PR and try to fix the issue.

**Comment by kdmurray91** [comment]
Thanks mate!

**Pull request merged**
