### PR TITLE
Skip sets with incorrect encoding

### PR DESCRIPTION
**Pull request by krig**
Some email may contain illegal characters according to the
encoding they specify.

Example error generated:

    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 3701: ordinal not in range(128)

With this change, any sets with mail that have errors like that
are skipped and counted in a separate rejection bin.

This at least lets the deduplication process continue processing
all the mail.

Resolves: #39
Resolves: #41

### CODE REVIEW

**Comment by kdeldycke** [comment]
That's a good one! I'll merge that right away and try to cut a release in the next few days.

**Comment by kdeldycke** [comment]
@krig : Do you have the full stack trace of the exception? If this PR is good enough for now, I'm not sure it is the `duplicates.check_differences()` call is the right place to catch `UnicodeDecodeError`, as it might be raised anywhere else in the code.

**Comment by krig** [comment]
I think I should be able to recreate it, yeah. Unfortunately I'm travelling for two weeks starting tomorrow, so I don't know if I can get it done before I get back home.

Thanks for merging, by the way!

**Comment by nhjm449** [comment]
I encountered this today, so here's a stack trace. v2.0.1, python 2.7

```
Check that mail differences are within the limits.
Traceback (most recent call last):
  File "/usr/local/python2.7/bin/mdedup", line 11, in <module>
    load_entry_point('maildir-deduplicate==2.0.1', 'console_scripts', 'mdedup')()
  File "/usr/local/python2.7/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/python2.7/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/python2.7/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/python2.7/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/python2.7/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/python2.7/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "build/bdist.linux-x86_64/egg/maildir_deduplicate/cli.py", line 194, in deduplicate
  File "build/bdist.linux-x86_64/egg/maildir_deduplicate/deduplicate.py", line 534, in run
  File "build/bdist.linux-x86_64/egg/maildir_deduplicate/deduplicate.py", line 141, in check_differences
  File "/usr/local/python2.7/lib/python2.7/site-packages/boltons/cacheutils.py", line 658, in __get__
    value = self.func(obj)
  File "build/bdist.linux-x86_64/egg/maildir_deduplicate/mail.py", line 92, in size
UnicodeDecodeError: 'ascii' codec can't decode byte 0xfc in position 145: ordinal not in range(128)
```

**Comment by kdeldycke** [comment]
Thanks @nhjm449 , that's what I suspected all along. Has to refactor a little bit in 0d71f59de44760f2736d1dac5ba296b4ed24448f to catch some edge-cases.

**Pull request merged**
