### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by Painted-Fox**
Hi @kdeldycke,

I started trying to use your script to help me find duplicates in my MailDir, but I ran into some issues.  I've been fixing them as I go along and this is the cumulation of all the fixes I have made so far.

I was using [OfflineIMAP](https://github.com/OfflineIMAP/offlineimap) and tried reorganizing the directories where I wanted all of my gmail folders after I had downloaded mail from this.  I believe this made OfflineIMAP confused and started uploading duplicates to gmail.

I've started trying to use [iSync](http://isync.sourceforge.net/) as a replacement for OfflineIMAP, and I hope that prevents creating duplicates from happening in the future, but I need a tool to help me find my duplicate emails.  That's how I came across maildir-deduplicate.

I want to thank you for creating the maildir-deduplicate tool, and I hope you (and possibly others) find my changes useful.

### CODE REVIEW

**Comment by kdeldycke** [comment]
Thanks a lot for your contributions! I'll merge them right away! :)

**Comment by Painted-Fox** [comment]
Thank you, @kdeldycke!

**Comment by kdeldycke** [comment]
FYI, v1.0.2 has been released: https://pypi.python.org/pypi/maildir-deduplicate/1.0.2

**Comment by Painted-Fox** [comment]
Great!  I see if I can add a package for it to [Nixpkgs](https://github.com/NixOS/nixpkgs).

**Pull request merged**
