### PR TITLE
Encoding issue

### PR DESCRIPTION
**Pull request by kdmurray91**
Hi @kdeldycke 

Since the changes we made yesterday I have been able to analyse a bigger set of my maildir. It appears that we missed a few encoding issues. The attached _seems_ to fix them, but checking this on another test-set (specifically a non-English maildir) would be wise.

Cheers,
K

### CODE REVIEW

**Comment by kdmurray91** [comment]
Looks like the approach I take is python-2 incompatible. Any ideas on how to port this @kdeldycke?

**Comment by kdeldycke** [comment]
Isn't it because [`message_from_binary_file` was introduced in Python 3.2](https://docs.python.org/3/library/email.parser.html#email.message_from_binary_file)?

In which case you should try to hard. Let's revert to the old behaviour for Python 2. What do you think?

**Comment by kdeldycke** [comment]
FYI, I've reverted to your previous behaviour in c96c027cb6edb589355c43d0ef40c3329155e6da for tests to pass in Python 2.

Can you try to rebase this PR on top of the `develop` branch?

**Comment by kdmurray91** [comment]
@kdeldycke Thanks heaps. I've rebased and pushed.

**Comment by kdeldycke** [comment]
Thanks. Tests still not passing though... :(

Is there a reason to not keep using the `get_payload()` method in 2e43a693e5a2b25f23920b64f38f37d2427114be ?

**Comment by kdmurray91** [comment]
Ah, not really, other than that it kept raising `UnicodeError` and going the route I did *always* worked (on python 3).

**Comment by kdeldycke** [comment]
Sorry to be ˈskeptical, it's just that it feels like the issue is a `.decode('utf-8')` away of being solved. That's why I'm not certain we need heavy-duty encoding guessing via `chardet`.

So here is what I propose: if you can isolate one message triggering a `UnicodeDecodeError`, I'll try to solve it through a much more restrained decoding path. In the mean time, I'll keep your current PR open and I'll merge it as a last resort. Unless you find a way to make the unittests pass in Python 2. What do you think?

**Comment by kdeldycke** [comment]
Handling of unparseable email has been added in #47, which supersedes and invalidates half of this PR. As a result, and because it's currently un mergeable as-is, I'll close this PR for now. Sorry @kdmurray91. :(

That being said, your effort was not vain as I pointed to your code in #46 as a possible way to enhance parsing of badly encoded mails.

**Pull request closed without merging**
