### PR TITLE
canonical_header_value: don't fail if mktime_tz does

### PR DESCRIPTION
**Pull request by jepler**
At the same time, unify 2 (would now be 3) try/except blocks into a single try/except block

Closes: #54

Signed-off-by: Jeff Epler <jepler@unpythonic.net>

### CODE REVIEW

**Comment by jepler** [comment]
so I tried writing a test for this, but it hits another problem (which I see on my real data too), namely an assertion error in `dedup.report()` and the duplicated old-timestamp messages aren't deleted either.  If I can't get a handle on that, I'll open a new report.

Specifically, the assertion firing is
~~~~
        assert self.stats['mail_kept'] == (
            self.stats['mail_unique'] +
            self.stats['mail_duplicates'])
~~~~
because it found 2, kept 2, unique 2, duplicates 2.

**Comment by jepler** [comment]
.. I pushed the version with the failing test.  Perhaps something here will be useful to further diagnose just what is going on; it goes beyond just the statistics being wrong.  Probably another layer where dates are parsed has not yet revealed itself.

**Comment by kdeldycke** [comment]
Thanks @jepler for this PR!

Stats accounting effectively seems a little bit broken as per #45.

**Comment by kdeldycke** [comment]
Sorry for the delay. Let's merge that fix upstream!

**Comment by jepler** [comment]
Thanks!

**Pull request merged**
